# Site settings
author: Maia Ngo
title: Maia's Blog
header-img: img/home-bg.png
email: maia.groundwatercapital@gmail.com
copyright_name: Maia Ngo
description: > # this means to ignore newlines until "baseurl:"
  Maia's Data Science journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MaiaNgo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
